from __future__ import annotations
import typing
__all__: list[str] = ['S63Client', 'S63Exception', 'createCellPermit', 'createUserPermit', 'decryptAndUnzipCellByKey', 'decryptCell', 'encryptCell', 'extractCellKeysFromCellpermit', 'extractHwIdFromUserpermit', 'validateCellPermit', 'zip']
class S63Client:
    def __init__(self, HW_ID: bytearray, M_KEY: bytearray, M_ID: bytearray) -> None:
        ...
    @typing.overload
    def decryptAndUnzipCell(self, in_path: str, out_path: str) -> None:
        ...
    @typing.overload
    def decryptAndUnzipCell(self, in_path: str, cellPermit: str, out_path: str) -> None:
        ...
    def getHWID(self) -> bytearray:
        ...
    def getMID(self) -> bytearray:
        ...
    def getMKEY(self) -> bytearray:
        ...
    def getUserpermit(self) -> str:
        ...
    def importPermitFile(self, permitFile: str) -> None:
        ...
    def installCellPermit(self, cellPermit: str) -> None:
        ...
    def open(self, s63cellpath: str) -> bytearray:
        ...
    def setHWID(self, HW_ID: bytearray) -> None:
        ...
    def setMID(self, M_ID: bytearray) -> None:
        ...
    def setMKEY(self, M_KEY: bytearray) -> None:
        ...
class S63Exception(Exception):
    pass
class zip:
    @staticmethod
    def unzip(data: bytearray) -> bytearray:
        ...
    @staticmethod
    def zip(filename: str, data: bytearray) -> bytearray:
        ...
def createCellPermit(HW_ID: bytearray, CK1: bytearray, CK2: bytearray, cellname: str, expiry_date: str) -> str:
    ...
def createUserPermit(M_KEY: bytearray, HW_ID: bytearray, M_ID: bytearray) -> str:
    ...
def decryptAndUnzipCellByKey(in_path: str, keys: tuple[bytearray, bytearray], out_path: str) -> None:
    ...
@typing.overload
def decryptCell(path: str, keys: tuple[bytearray, bytearray]) -> bytearray:
    ...
@typing.overload
def decryptCell(buf: bytearray, key: bytearray) -> bytearray:
    ...
def encryptCell(buf: bytearray, key: bytearray) -> bytearray:
    ...
def extractCellKeysFromCellpermit(cellpermit: str, HW_ID: bytearray) -> tuple[bytearray, bytearray]:
    ...
def extractHwIdFromUserpermit(userpermit: str, M_KEY: bytearray) -> bytearray:
    ...
def validateCellPermit(permit: bytearray, HW_ID: bytearray) -> bool:
    ...
